### ISSUE TITLE
Javascript console.log error

### ISSUE THREAD

**Issue by aidanw1** [thecodercoder/gulp-for-beginners#5]
Hi, I have recently been doing your gulp course and get an error on the first javascript module its not showing the 2 console.logs for script.js and script.js2.

Firefox: The resource from “http://127.0.0.1:5500/dist/script.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
Chrome - script.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by aidanw1** [comment]
oops i had script.js instead of scripts.js in my index.html

**Comment by thecodercoder** [comment]
Glad you were able to resolve it!
